
#if __has_include("AppMetricaTestUtils.h")
    #import "AMADateProviderMock.h"
    #import "AMAHTTPRequestsFactoryMock.h"
    #import "AMAHTTPSessionProviderMock.h"
    #import "AMAIncrementableValueStorageMock.h"
    #import "AMALocaleMock.h"
    #import "AMAModuleBundleProvider.h"
    #import "AMAMutableSKPaymentTransaction.h"
    #import "AMAMutableSKProduct.h"
    #import "AMAStubHostAppStateProvider.h"
    #import "AMATestAssertionHandler.h"
    #import "AMATestExecutor.h"
    #import "AMATestNetwork.h"
    #import "AMATestSafeTransactionRollbackContext.h"
    #import "AMATestTruncator.h"
    #import "AMATestURLProtocol.h"
    #import "AMATestUtilities.h"
    #import "AMAUserDefaultsMock.h"
    #import "CLLocation+TestUtilities.h"
#else
    #import <AppMetricaTestUtils/AMADateProviderMock.h>
    #import <AppMetricaTestUtils/AMAHTTPRequestsFactoryMock.h>
    #import <AppMetricaTestUtils/AMAHTTPSessionProviderMock.h>
    #import <AppMetricaTestUtils/AMAIncrementableValueStorageMock.h>
    #import <AppMetricaTestUtils/AMALocaleMock.h>
    #import <AppMetricaTestUtils/AMAModuleBundleProvider.h>
    #import <AppMetricaTestUtils/AMAMutableSKPaymentTransaction.h>
    #import <AppMetricaTestUtils/AMAMutableSKProduct.h>
    #import <AppMetricaTestUtils/AMAStubHostAppStateProvider.h>
    #import <AppMetricaTestUtils/AMATestAssertionHandler.h>
    #import <AppMetricaTestUtils/AMATestExecutor.h>
    #import <AppMetricaTestUtils/AMATestNetwork.h>
    #import <AppMetricaTestUtils/AMATestSafeTransactionRollbackContext.h>
    #import <AppMetricaTestUtils/AMATestTruncator.h>
    #import <AppMetricaTestUtils/AMATestURLProtocol.h>
    #import <AppMetricaTestUtils/AMATestUtilities.h>
    #import <AppMetricaTestUtils/AMAUserDefaultsMock.h>
    #import <AppMetricaTestUtils/CLLocation+TestUtilities.h>
#endif
